#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 12 16:42:12 2021

@author: hiepbk
"""

for letter in 'Python':     # Vi du dau tien
   print( 'Chu cai hien tai :', letter)

qua = ['chuoi', 'tao',  'xoai']
for qua in qua:        # Vi du thu hai
   print ('Ban co thich an :', qua)

print ("Good bye!")

#%%
dict = {'Ten': 'Hoang', 'Tuoi': 7};

print ("dict['Ten']: ", dict['Ten'])